In [80]:
import numpy as np

## Aşağıdaki arr1 arrayinin orta satırını ve son sütunu seçin:

In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr1[1:]

array([[4, 5, 6],
       [7, 8, 9]])

## Arrayin son satırını ters çevirerek seçin:

In [7]:
arr1[2][::-1]

array([9, 8, 7])

## Arrayin köşegen elemanlarını seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [8]:
np.diag(arr1)

array([1, 5, 9])

## Arrayin alt üçgenini seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [9]:
np.tril(arr1)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

## Arrayin üst üçgenini seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [10]:
np.triu(arr1)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

## Arrayin elemanlarını rastgele karıştırarak seçin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [21]:
flattened = arr1.flatten()

In [22]:
np.random.shuffle(flattened)
flattened

array([5, 2, 1, 3, 4, 8, 6, 7, 9])

In [23]:
 # flattened.reshape(3,3)

## Aşağıdaki arr2D dizisini, 2. satırını arr1D dizisi ile toplayacak şekilde update edin.:

In [33]:
arr2D = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr1D = np.array([10, 20, 30])

display(arr2D)
display(arr1D)

array([[1, 2, 3],
       [4, 5, 6]])

array([10, 20, 30])

In [32]:
arr2D[1, :] + arr1D

array([14, 25, 36])

In [34]:
arr2D[1, :] += arr1D
arr2D

array([[ 1,  2,  3],
       [14, 25, 36]])

## Aşağıdaki arr2 arrayinin satırlarını toplayarak seçin:

In [35]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
np.sum(arr2, axis=1)

array([10, 26, 42, 58])

## Arrayin 3. satırındaki en büyük ve en küçük elemanları seçin:

In [44]:
np.min(arr2[2]) 

9

In [43]:
np.min(arr2[2, :])

9

In [42]:
np.max(arr2[2])

12

## Aşağıdaki arr3 arrayinin 5'ten küçük elemanlarını olduğu gibi, diğer elemanları 10 ile çarparak getirin:

**Derste görülenlere ilave araştırma gerektirebilir.**

In [46]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.where(arr3 < 5, arr3 *10) # numpy.where(condition, [x, y, ]/)

ValueError: either both or neither of x and y should be given

In [51]:
np.where(arr3 < 5, arr3, arr3 *10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# Aşağıdaki arr4 array'inin 1. ve 3. sütunlarındaki 5'ten büyük elemanlarını olduğu gibi, bu sütunların diğer elemanlarını 0 olarak getirin:
**Derste görülenlere ilave araştırma gerektirebilir.**

In [89]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
np.where(arr4 > 5, arr4, arr4 * 0) # false

array([[ 0,  0,  0,  0],
       [ 0,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [91]:
np.where(arr4 > 5, arr4, arr4 == 0) # np.where(arr4 > 5, arr4, arr4 = 0) gives an error #false

array([[ 0,  0,  0,  0],
       [ 0,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
np.where(arr4[:, [0]] > 5, arr4, arr4 * 0) # false

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
np.where(arr4[:, [0, 2]] > 5, arr4[:, [0, 2]], 0) 

array([[ 0,  0],
       [ 0,  7],
       [ 9, 11],
       [13, 15]])

In [94]:
arr4[:, [0, 2]] = np.where(arr4[:, [0, 2]] > 5, arr4[:, [0, 2]], 0)
arr4

array([[ 0,  2,  0,  4],
       [ 0,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Arrayin 1. ve 4. sütunlarındaki 10'dan büyük ve eşit elemanları "büyük", bu sütunların diğer elemanlarını "küçük" olarak değiştirin:

**Derste görülenlere ilave araştırma gerektirebilir.**

In [95]:
np.where((arr4[:, 0] >= 10) | (arr4[:, 3] >= 10), 'büyük', 'küçük')

array(['küçük', 'küçük', 'büyük', 'büyük'], dtype='<U5')

In [79]:
result = np.where((arr4[:, 0] >= 10) | (arr4[:, 3] >= 10), 'büyük', 'küçük')
result

array(['küçük', 'küçük', 'büyük', 'büyük'], dtype='<U5')

In [96]:
arr4_büyük = np.where((arr4[:, [0,3]] >= 10) , "büyük", "kücük")
arr4_büyük

array([['kücük', 'kücük'],
       ['kücük', 'kücük'],
       ['kücük', 'büyük'],
       ['büyük', 'büyük']], dtype='<U5')

In [ ]:
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])