<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

# <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Tasks for Session-1</p>

## Task 1 : Task: Random Matrix Generation and Operations:

### 1a. Generate a 4x4 matrix filled with random values.

In [1]:
import numpy as np

In [11]:
np.random.rand(4,4)

array([[0.42064597, 0.26096724, 0.67392308, 0.85901742],
       [0.21656658, 0.28942586, 0.19579302, 0.77921975],
       [0.03009816, 0.48347465, 0.30102683, 0.56272886],
       [0.93987443, 0.95055332, 0.27896127, 0.6790401 ]])

In [18]:
np.random.randn(16)

array([-0.32219018, -1.32199116, -2.04518132, -2.07000403,  0.15866066,
       -0.04449305, -0.10916259, -0.5984306 , -1.05982871,  1.59160779,
       -0.45763042, -0.19271981,  2.62837142, -0.01146208, -0.476097  ,
       -1.10355317])

In [19]:
np.random.randn(4,4)

array([[ 1.16275481, -0.61798853,  1.17183532,  1.28312121],
       [-0.17919908, -0.3851088 ,  0.25660317,  0.58478937],
       [-0.40891865,  0.39538284, -1.22002802,  0.0702698 ],
       [-0.20204998, -0.58519076, -2.56612883, -1.10404666]])

In [3]:
matrix = np.random.randn(4,4)
matrix

array([[ 1.11169803,  0.08075051,  0.58042714,  0.97608799],
       [ 0.90124324, -0.87802917, -1.12052556,  0.04240482],
       [ 0.50571722, -1.00285548,  0.60720031,  0.83093323],
       [ 1.27263013, -0.93479151,  1.40696651,  0.24205307]])

### 1b. Calculate the row sums of the matrix.

In [21]:
np.sum(matrix, axis=1)

array([-2.39542589,  0.97478124, -0.43538362, -4.01488438])

### 1c. Calculate the column means of the matrix.

In [4]:
np.mean(matrix, axis=0)

array([ 0.94782215, -0.68373141,  0.3685171 ,  0.52286978])

### 1d. Find the sum of the diagonal elements of the matrix.

In [68]:
np.trace(matrix)

-2.2376340100990593

## Task 2: Array Sorting and Indexing:

### 2a. Create an array of random numbers from 1 to 20.

In [34]:
np.array(range(1,21))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
np.random.randint(1,21,(1,20))

array([[ 8,  4, 12,  2, 15, 17, 15, 10, 13, 18, 13,  4,  8,  1, 18,  2,
         1, 19,  5, 16]])

In [70]:
np.random.randint(1,21, size=20)

array([ 9, 10, 19,  4,  5,  1, 17,  4, 10, 17,  8, 15,  1, 19, 10,  1, 13,
       17,  4, 20])

In [69]:
np.random.randint(1,21)

11

### 2b. Sort the array in descending order.

In [ ]:
np.sort(array)[::1]

In [73]:
np.sort(np.random.randint(1,21,(1,20)), ascending=False)

NameError: name 'false' is not defined

In [45]:
np.sort(np.random.randint(1,21,(1,20)))[::-1]

array([[ 3,  3,  3,  5,  6,  6,  7,  7,  8, 11, 11, 12, 13, 14, 14, 14,
        15, 19, 20, 20]])

In [38]:
np.sort([ 8,  4, 12,  2, 15, 17, 15, 10, 13, 18, 13,  4,  8,  1, 18,  2,
         1, 19,  5, 16])[::-1]

array([19, 18, 18, 17, 16, 15, 15, 13, 13, 12, 10,  8,  8,  5,  4,  4,  2,
        2,  1,  1])

### 2c. Find the minimum and maximum elements of the array.

In [48]:
array1 = np.array([19, 18, 18, 17, 16, 15, 15, 13, 13, 12, 10,  8,  8,  5,  4,  4,  2,
        2,  1,  1])
array1.min()

1

In [49]:
array1.max()

19

### 2d. Select the first half of the array (the first 10 elements) and reverse them.

In [ ]:
half_array = array[:len(array)//2]

reversed_half_array = half_array[::-1]

print(array)
print(reversed_half_array)

In [56]:
array1[:10][::-1]

array([12, 13, 13, 15, 15, 16, 17, 18, 18, 19])

## Task 3: Convert the Arrays:

### 3a. Create an array with elements [-1, 0, 1, 2, 3].

In [97]:
my_array =  [-1, 0, 1, 2, 3]
my_array

[-1, 0, 1, 2, 3]

In [102]:
my_array2 = np.array([-1, 0, 1, 2, 3])
my_array

[-1, 0, 1, 2, 3]

### 3b. Convert the array into a matrix and square each element.

In [ ]:
matrix = np.reshape(array, (1, -1))
# matrix = np.matrix(array)  # alternative solution
print(matrix)

squared_matrix = np.square(matrix)
print(squared_matrix)

In [103]:
np.matrix(my_array2)

matrix([[-1,  0,  1,  2,  3]])

In [107]:
np.square([my_array2]) #!

array([[1, 0, 1, 4, 9]])

In [105]:
my_array2.reshape(1,-1)

array([[-1,  0,  1,  2,  3]])

### 3c. Convert the matrix back to a one-dimensional array.

In [ ]:
np.reshape(array, (5,))

In [106]:
np.ravel(my_array)

array([-1,  0,  1,  2,  3])

### 3d. Convert each element of the array to its absolute value

In [ ]:
abs_array = np.abs(array)
abs_array

In [108]:
np.absolute(my_array)

array([1, 0, 1, 2, 3])

<hr>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of Task</p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>